matrix:
  fast_finish: true

environment:
  matrix:
  - os: Visual Studio 2013
    Compiler: msvc
    Config: Release
    vcmode: release
    vcversion: 2013
  - os: Visual Studio 2015
    Compiler: msvc
    Config: Release
    vcmode: release
    vcversion: 2015

build_script:
  - cmd: vcbuild ia32 nosign "%vcmode%" "%vcversion%"

deploy:
  provider: FTP
  host: ftp.saper.info
  username: ftp
  password: ftp
  folder: incoming/node/builds/$(appveyor_build_version)
