os: Visual Studio 2015

matrix:
  fast_finish: true

environment:
  matrix:
  - os: Visual Studio 2013
    Compiler: msvc
    Config: Release
    vcmode: release
    vcversion: 2013
  - os: Visual Studio 2015
    Compiler: msvc
    Config: Release
    vcmode: release
    vcversion: 2015

build_script:
  - cmd: vcbuild ia32 nosign $(vcmode) $(vcversion)

artifacts:
  - path: $(Config)
    name: node-$(vcmode)-$(vcversion)-$(APPVEYOR_REPO_COMMIT)
    type: zip

deploy:
  provider: FTP
  host: ftp.saper.info
  username: ftp
  password: ftp
  folder: /incoming/node/builds
  artifact:
